### PR TITLE
Update Dockerfile with MCR image

### PR DESCRIPTION
**Pull request by dlepow**
Substituting equivalent .NET core image from mcr.microsoft.com

## Purpose
Updating Dockerfile to pull Microsoft image from the recommended registry for first-party images instead of from Docker Hub. If questions about this change, please contact danlep (MSFT).
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x ] No
```
Should not be a breaking change. Testing is recommended to confirm.

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by dlepow** [comment]
@caleteet @PatAltimore - Can you please review this PR when you have a chance? Many thanks!

**Review by PatAltimore — APPROVED** [review]
Looks good to me.

**Comment by PatAltimore** [comment]
@caleteet, Do you want to take a look?

**Comment by caleteeter** [comment]
@PatAltimore looks good to me as well!

**Review by caleteeter — APPROVED** [review]

**Pull request merged**
