### PR TITLE
moving devkit

### PR DESCRIPTION
**Pull request by cnsegura**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by cnsegura** [comment]
fixed

**Comment by cnsegura** [comment]
Hey Ali, sorry had to resubmit this PR again to fix some errors that wouldn't resolve automatically - this should be good to go once you approve

**Comment by ali92hm** [comment]
@cnsegura I was wondering if we should delete these files from the git history as well in order to reduce the size of the repo. Let me know what you think.

**Comment by cnsegura** [comment]
@ali92hm - sure, we have the recent snapshot already loaded to the new location. No reason to keep the history. Do you need me to change the PR?

**Pull request merged**
